### ISSUE TITLE
README.md misleading

### ISSUE THREAD

**Issue by almereyda** [valueflows/software-list#3]
We'd actually only need slight modifications. Who wants first?

**Comment by fosterlynn** [comment]
@almereyda just want to make sure I understand - this is about the thought some of us had to create a list of software that supports alternative/solidarity/etc. movements and groups?  Any continuing relationship to Solid?  (Sorry for being kind of behind...)

**Comment by almereyda** [comment]
Yes, after struggling with choosing either staticsitegenerators.net or
conceptviz.github.io as an interface, I've found the minimal template very
appealing and extensible. Collaboration on this codebase, i.e. tagging and
sortability, felt more natural in terms of a flat hierarchy other than the
other two approaches. Also seperating data and visualization felt natural.
libreprojects already does this, but in one repo.

And yes, linking to SoLiD only happened accidentally as I've found the
source repo within their premises.

**Comment by fosterlynn** [comment]
I made a few changes to make it reflect the proposed software list.

@almereyda I just edited and committed in place, hope that is OK with you for a workflow for this type of thing.  (Branch and pull request for more significant changes or if need review.)

**Comment by almereyda** [comment]
We have moved the ValueFlows GitHub organization to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at https://lab.allmende.io/valueflows/software-list/-/issues/3.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
